AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 Automation with Java, GitHub App Clone, and Auto Shutdown

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Stage of the deployment

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroups:
        - !Ref EC2SecurityGroup
      ImageId: !Sub "{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}"
      Tags:
        - Key: Stage
          Value: !Ref Stage
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y java-21-amazon-corretto git at
          cd /home/ec2-user
          git clone https://github.com/techeazy-consulting/techeazy-devops.git
          cd techeazy-devops
          echo "Shutting down in 15 minutes to save cost"
          echo "shutdown -h now" | at now + 15 minutes

Outputs:
  InstancePublicIP:
    Description: Public IP of the deployed EC2
    Value: !GetAtt EC2Instance.PublicIp
